# Generated by cpputils-cmake.
include /Users/sangjee/code/workspace/torchpp/build/CMakeFiles/example-app.dir/flags.make
.PHONY: check-syntax
check-syntax:
	${CXX} -o /dev/null ${CXX_FLAGS} ${CXX_DEFINES} ${CXX_INCLUDES}  -S ${CHK_SOURCES}